import Head from 'next/head'
import {useEffect, useState} from "react";
import Link from 'next/link';
import Button from "../components/button";
import Inventory from "../components/inventory";

export default function Home({ data }) {


  const [email, setEmail] = useState('');
  const [username, setUsername] = useState('');
  const [ users, setUsers ] = useState([]);


  useEffect(() => {
    setUsers(data);
  }, [])

  const sendData = async () => {
    fetch('http://localhost:3000/api/User',{
      method: 'POST',
      headers: {
        "Content-Type" : "application/json"
      },
      body: JSON.stringify({ email: email, username: username })
    }).then(res => res.json()).then(data => setUsers(data.data)).catch(e => e.message);
    setEmail('');
    setUsername('');
  };

  const handleSubmit = (e) => {
    e.preventDefault()
    sendData();
  };

  const handleDelete = async (id) => {
    fetch('http://localhost:3000/api/User',{
      method: 'DELETE',
      headers: {
        "Content-Type" : "application/json"
      },
      body: JSON.stringify({ userId: id })
    }).then(res => res.json()).then(data => console.log(data)).catch(e => e.message);
    const data = users.filter( user => user._id !== id);
    setUsers(data);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form onSubmit={(e) => handleSubmit(e)} style={{ margin: 10 }}>
          <input type="text" placeholder={"Email"} value={email} onChange={({target}) => setEmail(target.value)}/>
          <input type="text" placeholder={"Username"} value={username} onChange={({target}) => setUsername(target.value)}/>
          <Button type={"submit"} value={"Submit"}/>
        </form>
      </main>
      <div>
        {users.map(user => (
            <div key={user._id}>
              <p>{user.email}</p>
              <p>{user.username}</p>
              <button onClick={ () => handleDelete(user._id)}>Delete</button>
              <Link href={`/${user._id}`}><a>View</a></Link>
              {/*<Inventory/>*/}
            </div>
        ))}
      </div>
    </div>
  )
}
export async function getServerSideProps(){
  const res = await fetch('http://localhost:3000/api/User',{
    method: 'GET',
    headers: {
      "Content-Type": "application/json"
    }
  });
  const data = await res.json();
  return {
    props: {
      data: data.results
    }
  }
}